src/ecommerce/carts/urls.py
from django.conf.urls import url

from .views import cartHome, cartUpdate, checkoutHome

urlpatterns = [
    url(r'^$', cartHome, name='home'),
    url(r'^update/$', cartUpdate, name='update'),
    url(r'^checkout/$', checkoutHome, name='checkout'),
]

src/ecommerce/ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

from .views import homepage, contactpage
from accounts.views import loginpage, registerpage, guestRegisterPage
from carts.views import cartHome
#from products.views import ProductFeaturedListView, ProductDetailView, ProductFeaturedDetailView

urlpatterns = [
    url(r'^$', homepage, name='home'),
    url(r'^contact/$', contactpage, name='contact'),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^login/$', loginpage, name='login'),
    url(r'^register/guest/$', guestRegisterPage, name='guestRegister'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', registerpage, name='register'),
    url(r'^cart/',  include("carts.urls", namespace='carts')),
    url(r'^admin/', admin.site.urls),

    #url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view(), name='product-details'),
    #url(r'^featured/$', ProductFeaturedListView.as_view(), name='featured'),
    #url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view(), name='featured-details'),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL ,document_root=settings.MEDIA_ROOT)

src/ecommerce/carts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import m2m_changed, pre_save

from products.models import Product
# Create your models here.

User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):

    def createNewOrGet(self, request):
        cartId = request.session.get("cartId", None)

        qs = self.get_queryset().filter(id=cartId)
        if qs.count() == 1:
            newObj = False
            cartObj = qs.first()
            print('Cart ID exists')
            if request.user.is_authenticated() and cartObj.user is None:
                cartObj.user = request.user
                cartObj.save()
        else:
            cartObj = Cart.objects.newCart(user=request.user)
            newObj = True
            request.session['cartId'] = cartObj.id 
        return cartObj, newObj

    def newCart(self, user=None):
        userObj = None
        if user is not None:
            if user.is_authenticated():
                userObj = user
        return self.model.objects.create(user=userObj)

    """ def get_queryset(self):
        return super().get_queryset().filter() """


class Cart(models.Model):
    user        = models.ForeignKey(User, null=True, blank=True)
    products    = models.ManyToManyField(Product, blank=True)
    subTotal    = models.DecimalField(default=0.00, max_digits=50, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=50, decimal_places=2)
    timestamp   = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)

def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        print(action)
        products = instance.products.all()
        cartTotal = 0
        for product in products:
            cartTotal += product.price
        print(cartTotal)
        if instance.subTotal != cartTotal:
            instance.subTotal = cartTotal
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)

def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subTotal > 0:
        instance.total = instance.subTotal + 10 #* 1.08
    else:
        instance.total = 0

pre_save.connect(pre_save_cart_receiver, sender=Cart)

src/ecommerce/carts/views.py
from django.shortcuts import render, redirect

from accounts.forms import LoginForm, GuestForm
from accounts.models import GuestEmail
from products.models import Product
from billing.models import BillingProfile
# Create your views here.
from .models import Cart
from orders.models import Order

# def cartCreate(user=None):
#     cartObj = Cart.objects.create(user=None)
#     print("New cart Id created")
#     return cartObj

def cartHome(request):
    cartObj, newObj = Cart.objects.createNewOrGet(request)
    return render(request, 'carts/home.html', {"cart":cartObj})

    # if cartId is None:#and isinstance(cartId, int):
    #     cartObj = Cart.objects.create(user=None)
    #     request.session['cartId'] = cartObj.id
    #     #print("new cerated",  request.session['cartId'])
    # else:
    #     print("Cart Id Exists.")
    #     cartObj = Cart.objects.get(id=cartId)
    #     #print(request.session.get('cartId'))

    # qs = Cart.objects.filter(id=cartId)
    # if qs.count() == 1:
    #     cartObj = qs.first()
    #     print('Cart ID exists')
    #     if request.user.is_authenticated() and cartObj.user is None:
    #         cartObj.user = request.user
    #         cartObj.save()
    # else:
    #     cartObj = Cart.objects.newCart(user=request.user)
    #     request.session['cartId'] = cartObj.id 

    

    #print(request.session.session_key)
    #request.session.set_expiry(300)

def cartUpdate(request):
    print(request.POST)
    productId = request.POST.get('productId')
    if productId is not None:

        try:
            productObj = Product.objects.get(id=productId)
        except Product.DoesNotExist:
            redirect("carts:home")
        
        cartObj, newObj = Cart.objects.createNewOrGet(request)
        if productObj in cartObj.products.all():
            cartObj.products.remove(productObj)
        else:
            cartObj.products.add(productObj)
        request.session['nItems'] = cartObj.products.all().count()
        print(request.session['nItems'])
    return redirect("carts:home")

def checkoutHome(request):
    cartObj, cartCreated = Cart.objects.createNewOrGet(request)
    print(cartObj, cartCreated)
    orderObj = None
    if cartCreated or cartObj.products.count() == 0:
        redirect("carts:home")
    else:
        orderObj, newOrderObj = Order.objects.get_or_create(cart=cartObj)
        print(orderObj, newOrderObj)
    
    user = request.user
    billingProfile = None
    loginForm = LoginForm()
    guestForm = GuestForm()
    guestEmailId = request.session.get('guestEmailId')

    if user.is_authenticated():
        billingProfile, bProfcreated = BillingProfile.objects.get_or_create(user=user, email=user.email)
    elif guestEmailId is not None:
        guestEmailObj = GuestEmail.objects.get(id=guestEmailId)
        billingProfile, guestProfcreated = GuestEmail.objects.get_or_create(email=guestEmailObj.email)
    else:
        pass
    
    context = {
        "object": orderObj,
        "billingProfile": billingProfile,
        "loginForm": loginForm,
        "guestForm": guestForm
        }
    return render(request, 'carts/checkout.html', context)

src/ecommerce/carts/templates/carts/checkout.html
{% extends 'base.html' %}

{% block content %}

{% if not billingProfile %}

    <div class='row'>
        <div class='col-12 col-md-6'>
            <h3 class-'lead'>Login</h3><hr>
            {% include 'accounts/snippets/form.html' with form=loginForm nextUrl=request.build_absolute_uri btnText='Login to Checkout'%}
        </div>
        <div class='col-12 col-md-6'>
            <h3 class-'lead'>Continue as Guest</h3><hr>
            {% url 'guestRegister' as guestRegsiterUrl %}
            {% include 'accounts/snippets/form.html' with form=guestForm nextUrl=request.build_absolute_uri action_url=guestRegsiterUrl btnText='Proceed to Checkout' %}
        </div>
    </div>

{% else %}

    <h1>Checkout</h1>
    <p>Cart Total: {{object.cart.total}}</p>
    <p>Shipping Total: {{object.shippingTotal}}</p>
    <p>Order Total: {{object.total}}</p>

{% endif %}

{% endblock content %}

src/ecommerce/carts/templates/carts/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Cart</h1>

{% if cart.products.exists %}
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Product Name</th>
                <th>Product Price</th>
            </tr>
        </thead>

        <tbody>
            {% for object in cart.products.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a href='{{object.get_absolute_url}}'>{{ object.title }}</a>{% include 'products/snippets/update-cart.html' with product=object cart=cartObj inCart=True %}</td>
                    <td>{{object.price }}</td>
                </tr>
            {% endfor %}

            <tr>
                <td colspan="2"></td>
                <td><strong>Subtotal</strong>  {{ cart.subTotal }}</td>
            </tr>

            <tr>
                <td colspan="2"></td>
                <td><strong>Total</strong>  {{ cart.total }}</td>
            </tr>

            <tr>
                    <td colspan="2"></td>
                    <td><a href='{% url "carts:checkout" %}' class="btn btn-success btn-lg">Checkout</a></td>
                </tr>
        </tbody>
    </table>
{% else %}
    Cart Is Empty!
{% endif %}



{% endblock content %}