src/ecommerce/carts/urls.py
from django.conf.urls import url

from .views import cartHome, cartUpdate, checkoutHome

urlpatterns = [
    url(r'^$', cartHome, name='home'),
    url(r'^update/$', cartUpdate, name='update'),
    url(r'^checkout/$', checkoutHome, name='checkout'),
]

src/ecommerce/ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

from .views import homepage, contactpage
from accounts.views import loginpage, registerpage, guestRegisterPage
from carts.views import cartHome
#from products.views import ProductFeaturedListView, ProductDetailView, ProductFeaturedDetailView

urlpatterns = [
    url(r'^$', homepage, name='home'),
    url(r'^contact/$', contactpage, name='contact'),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^login/$', loginpage, name='login'),
    url(r'^register/guest/$', guestRegisterPage, name='guestRegister'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', registerpage, name='register'),
    url(r'^cart/',  include("carts.urls", namespace='carts')),
    url(r'^admin/', admin.site.urls),

    #url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view(), name='product-details'),
    #url(r'^featured/$', ProductFeaturedListView.as_view(), name='featured'),
    #url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view(), name='featured-details'),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL ,document_root=settings.MEDIA_ROOT)

src/ecommerce/products/urls.py
from django.conf.urls import url

from .views import ProductListView, ProductSlugView

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductSlugView.as_view(), name='detail'),
]

src/ecommerce/templates/base/css.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

src/ecommerce/templates/base/js.html
{% load static %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

src/ecommerce/templates/base/navbar.html
{% url 'home' as homeUrl %}
{% url 'contact' as contactUrl %}
{% url 'products:list' as productsUrl %}
{% url 'login' as loginUrl %}
{% url 'logout' as logoutUrl %}
{% url 'register' as registerUrl %}

{% url 'carts:home' as cartUrl %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
<div class="container">
  <a class="navbar-brand" href="{{homeUrl}}">
   <img src="https://www.getbootstrap.com/docs/4.3/assets/brand/bootstrap-solid.svg" width="30" height="30" alt="">
    {% if brandName %}  &nbsp;{{ brandName }} {% else %} Django eCommerce {% endif %}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == homeUrl %}active{% endif %}">
        <a class="nav-link" href="{{homeUrl}}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == contactUrl %}active{% endif %}">
        <a class="nav-link" href="{{contactUrl}}">Contact</a>
      </li>
      
      <li class="nav-item {% if request.path == productsUrl %}active{% endif %}">
        <a class="nav-link" href="{{productsUrl}}">Products</a>
      </li>
      <li class="nav-item {% if request.path == cartUrl %}active{% endif %}">
         <a class="nav-link" href="{{cartUrl}}"><i class="fa fa-shopping-cart"></i>  <small>({{ request.session.nItems }})</small></a>
        </li>
      {% if request.user.is_authenticated %}
        <li class="nav-item {% if request.path == loginUrl %}active{% endif %}">
         <a class="nav-link" href="{{logoutUrl}}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item {% if request.path == registerUrl %}active{% endif %}">
         <a class="nav-link" href="{{registerUrl}}">Register</a>
        </li>
        <li class="nav-item {% if request.path == loginUrl %}active{% endif %}">
         <a class="nav-link" href="{{loginUrl}}">Login</a>
        </li>

        
      {% endif %}
      
    </ul>
    
    {% include 'search/snippets/search-form.html' %}
  </div>
  </div>
</nav>